name: devkit_example
description: Example app for devkit.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blackbox:
    path: ..        # points to the devkit folder above
  dio: ^5.0.0
