name: blackbox_example
description: Example app for blackbox.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blackbox:
    path: ..        # points to the blackbox folder above
  dio: ^5.0.0
  shared_preferences: ^2.5.0
