// Auto-generated by: dart run flutter_blackbox:init --generate
// Re-run to regenerate after adding new libraries.
// ignore_for_file: depend_on_referenced_packages

import 'dart:convert';

import 'package:flutter_blackbox/flutter_blackbox.dart';
import 'package:dio/dio.dart';
import 'package:shared_preferences/shared_preferences.dart';

// ── DioBlackBoxAdapter ────────────────────────────────────────────────────────
// Connects your Dio instance to BlackBox's network inspector and mock engine.
// Auto-generated — safe to modify.

class DioBlackBoxAdapter extends BlackBoxHttpAdapter {
  DioBlackBoxAdapter(this._dio);

  final Dio _dio;
  _BlackBoxDioInterceptor? _interceptor;

  @override
  String get name => 'dio';

  @override
  void attach() {
    _interceptor = _BlackBoxDioInterceptor(adapter: this);
    _dio.interceptors.add(_interceptor!);
  }

  @override
  void detach() {
    if (_interceptor != null) {
      _dio.interceptors.remove(_interceptor!);
      _interceptor = null;
    }
  }
}

class _BlackBoxDioInterceptor extends Interceptor {
  _BlackBoxDioInterceptor({required this.adapter});

  final DioBlackBoxAdapter adapter;
  int _idCounter = 0;

  @override
  Future<void> onRequest(
    RequestOptions options,
    RequestInterceptorHandler handler,
  ) async {
    final id = 'dio_${_idCounter++}_${DateTime.now().millisecondsSinceEpoch}';
    options.extra['blackbox_request_id'] = id;
    options.extra['blackbox_start_ms'] = DateTime.now().millisecondsSinceEpoch;

    adapter.onRequest(NetworkRequest(
      id: id,
      method: options.method,
      url: '${options.baseUrl}${options.path}',
      timestamp: DateTime.now(),
      headers: _sanitiseHeaders(options.headers),
      body: _encodeBody(options.data),
      queryParameters:
          options.queryParameters.map((k, v) => MapEntry(k, v.toString())),
    ));

    final fullUrl = '${options.baseUrl}${options.path}';
    final mock = await adapter.intercept(options.method, fullUrl);

    if (mock != null) {
      final startMs = options.extra['blackbox_start_ms'] as int;
      final durationMs = DateTime.now().millisecondsSinceEpoch - startMs;
      final mockBody = mock.body;
      adapter.onResponse(NetworkResponse(
        requestId: id,
        statusCode: mock.statusCode,
        durationMs: durationMs,
        body: mockBody,
        headers: mock.headers,
        responseSizeBytes: _estimateSize(mockBody),
      ));
      return handler.resolve(
        Response<dynamic>(
          requestOptions: options,
          statusCode: mock.statusCode,
          data: mock.body,
          headers:
              Headers.fromMap(mock.headers.map((k, v) => MapEntry(k, [v]))),
        ),
        true,
      );
    }

    handler.next(options);
  }

  @override
  void onResponse(
      Response<dynamic> response, ResponseInterceptorHandler handler) {
    final body = _encodeBody(response.data);
    _recordResponse(
      requestOptions: response.requestOptions,
      statusCode: response.statusCode ?? 0,
      headers:
          _sanitiseHeaders(Map<String, dynamic>.from(response.headers.map)),
      body: body,
      responseSizeBytes: _estimateSize(body),
    );
    handler.next(response);
  }

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    final id = err.requestOptions.extra['blackbox_request_id'] as String?;
    final startMs = err.requestOptions.extra['blackbox_start_ms'] as int?;
    if (id == null) {
      handler.next(err);
      return;
    }
    final durationMs =
        startMs != null ? DateTime.now().millisecondsSinceEpoch - startMs : 0;

    NetworkFailureType type = NetworkFailureType.connection;
    if (err.type == DioExceptionType.connectionTimeout ||
        err.type == DioExceptionType.receiveTimeout ||
        err.type == DioExceptionType.sendTimeout) {
      type = NetworkFailureType.timeout;
    } else if (err.type == DioExceptionType.badResponse) {
      type = NetworkFailureType.server;
    }

    final errBody = err.response?.data;
    adapter.onResponse(NetworkResponse(
      requestId: id,
      statusCode: err.response?.statusCode ?? 0,
      headers: err.response != null
          ? _sanitiseHeaders(
              Map<String, dynamic>.from(err.response!.headers.map))
          : const {},
      body: errBody,
      durationMs: durationMs,
      failureType: type,
      responseSizeBytes: _estimateSize(errBody),
    ));
    handler.next(err);
  }

  void _recordResponse({
    required RequestOptions requestOptions,
    required int statusCode,
    required Map<String, String> headers,
    dynamic body,
    int? responseSizeBytes,
  }) {
    final id = requestOptions.extra['blackbox_request_id'] as String?;
    final startMs = requestOptions.extra['blackbox_start_ms'] as int?;
    if (id == null) return;
    final durationMs =
        startMs != null ? DateTime.now().millisecondsSinceEpoch - startMs : 0;
    adapter.onResponse(NetworkResponse(
      requestId: id,
      statusCode: statusCode,
      durationMs: durationMs,
      headers: headers,
      body: body,
      responseSizeBytes: responseSizeBytes,
    ));
  }

  int? _estimateSize(dynamic body) {
    if (body == null) return null;
    try {
      if (body is String) return body.length;
      return jsonEncode(body).length;
    } catch (_) {
      return body.toString().length;
    }
  }

  Map<String, String> _sanitiseHeaders(Map<String, dynamic> raw) {
    const redacted = {'authorization', 'cookie', 'set-cookie', 'x-api-key'};
    return {
      for (final e in raw.entries)
        e.key: redacted.contains(e.key.toLowerCase())
            ? '*** redacted ***'
            : e.value.toString(),
    };
  }

  dynamic _encodeBody(dynamic body) {
    if (body == null) return null;
    if (body is String) return body;
    if (body is Map || body is List) return body;
    try {
      return jsonDecode(body.toString());
    } catch (_) {
      return body.toString();
    }
  }
}

// ── SharedPrefsStorageAdapter ─────────────────────────────────────────────────
// Exposes SharedPreferences in the BlackBox Storage panel.
// Auto-generated — safe to modify.

class SharedPrefsStorageAdapter extends BlackBoxStorageAdapter {
  @override
  String get name => 'SharedPreferences';

  @override
  Future<Map<String, dynamic>> readAll() async {
    final prefs = await SharedPreferences.getInstance();
    return {for (final key in prefs.getKeys()) key: prefs.get(key)};
  }

  @override
  Future<void> write(String key, dynamic value) async {
    final prefs = await SharedPreferences.getInstance();
    if (value is bool) {
      await prefs.setBool(key, value);
    } else if (value is int) {
      await prefs.setInt(key, value);
    } else if (value is double) {
      await prefs.setDouble(key, value);
    } else if (value is String) {
      await prefs.setString(key, value);
    } else if (value is List<String>) {
      await prefs.setStringList(key, value);
    } else {
      await prefs.setString(key, value.toString());
    }
  }

  @override
  Future<void> delete(String key) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(key);
  }

  @override
  Future<void> clear() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.clear();
  }
}

/// Call this in your main() before runApp().
///
/// ```dart
/// void main() {
///   setupBlackBox(dio: myDio);
///   runApp(const BlackBoxOverlay(child: MyApp()));
/// }
/// ```
void setupBlackBox({required Dio dio}) {
  BlackBox.setup(
    httpAdapters: [DioBlackBoxAdapter(dio)],
    storageAdapters: [SharedPrefsStorageAdapter()],
    logAdapter: PrintLogAdapter(),
    trigger: const BlackBoxTrigger.floatingButton(),
    enabled: true, // wrap with kDebugMode if needed
  );
}
